package:
  name: hdf5
  version: 1.8.20

source:
  fn: hdf5-1.8.20.tar.bz2
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.20/src/hdf5-1.8.20.tar.bz2
  md5: 23078d57975903e9536d1e7b299cc39c

build:
  number: 0

requirements:
  build:
    - zlib
  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)
