package:
  name: libnetcdff
  version: 4.4.4

source:
  fn: netcdf-fortran-4.4.4.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.4.tar.gz
  md5: e855c789cd72e1b8bc1354366bf6ac72

requirements:
  build:
    - libnetcdf 4.4.1
    - curl
    - hdf5
    - zlib
  run:
    - libnetcdf 4.4.1
    - curl
    - hdf5
    - zlib

test:
  commands:
    - ncdump
    - nc-config --help

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
