package:
  name: zlib
  version: 1.2.11

source:
  fn: zlib-1.2.11.tar.gz
  url: http://zlib.net/zlib-1.2.11.tar.gz
  md5: 

build:
  number: 1

about:
  home: http://zlib.net/
  license: zlib (http://zlib.net/zlib_license.html)
  summary: "A Massively Spiffy Yet Delicately Unobtrusive Compression Library"
